apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: "PLACEHOLDER_TENANT_ID"
      vaultUrl: "https://PLACEHOLDER_VAULT.vault.azure.net"
      serviceAccountRef:
        name: eso-service-account
        namespace: external-secrets
