apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: database-dev
      server:
        # Since it's the same cluster, we can point to the default service
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-service-account
          namespace: external-secrets
