apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Secret
      name: azure-dns-config
    patch: |-
      - op: replace
        path: /stringData/azure.json
        value: |
          {
            "tenantId": "PROD_TENANT_ID",
            "subscriptionId": "PROD_SUBSCRIPTION_ID",
            "resourceGroup": "rg-prod-dns",
            "useWorkloadIdentityExtension": true
          }
