apiVersion: v1
kind: Secret
metadata:
  name: azure-dns-config
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "TENANT_ID",
      "subscriptionId": "SUBSCRIPTION_ID",
      "resourceGroup": "RESOURCE_GROUP",
      "useWorkloadIdentityExtension": true
    }
