apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Secret
      name: azure-dns-config
    patch: |-
      - op: replace
        path: /stringData/azure.json
        value: |
          {
            "tenantId": "012c6d21-cad3-4e61-98dd-2bc660a112b8",
            "subscriptionId": "32dade7a-ad90-464c-a9f3-27221e9f9d73",
            "resourceGroup": "rg-dns",
            "useWorkloadIdentityExtension": true
          }
