apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tim-db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  
  inheritedMetadata:
    labels:
      azure.workload.identity/use: "true"

  serviceAccountTemplate:
    metadata:
      annotations:
        azure.workload.identity/client-id: "PLACEHOLDER_CLIENT_ID"
      labels:
        azure.workload.identity/use: "true"

  storage:
    size: 20Gi
    storageClass: managed-csi-premium

  backup:
    barmanObjectStore:
      destinationPath: "https://PLACEHOLDER_STORAGE.blob.core.windows.net/backups"
      azureCredentials:
        storageAccount:
          name: storage-creds
          key: accountName
        inheritFromAzureAD: true
