apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-service-account
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
