apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-service-account
  namespace: database-dev
  annotations:
    azure.workload.identity/client-id: "13a33503-398c-4627-a1be-e96b2ef6c702"
  labels:
    azure.workload.identity/use: "true"
