apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Pointing directly to the remote YAML
    repoURL: 'https://github.com/kubernetes-sigs/gateway-api.git'
    targetRevision: v1.2.0
    path: config/crd/standard 
  destination:
    server: 'https://kubernetes.default.svc'
    # CRDs are cluster-scoped, but Argo needs a namespace target
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # CRITICAL: Gateway API CRDs are too large for standard kubectl apply
      - ServerSideApply=true
      # Ensures CRDs are created before other resources in the same app
      - SkipDryRunOnMissingResource=true