apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-disk
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain # CRITICAL: This keeps the data if the cluster is destroyed
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer